services:
  postgres:
    image: postgres:15
    container_name: LMS_System
    environment:
      POSTGRES_DB: LMS_System
      POSTGRES_USER: LMS_System_user
      POSTGRES_PASSWORD: admin1234
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  keycloak_db:
    image: postgres:15
    container_name: keycloak_db
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak_user
      POSTGRES_PASSWORD: keycloak_pass
    ports:
      - "5434:5432"
    volumes:
      - keycloak_pg_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL_HOST: keycloak_db
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak_user
      KC_DB_PASSWORD: keycloak_pass
    command: start-dev
    ports:
      - "8080:8080"
    depends_on:
      - keycloak_db

  minio:
    image: quay.io/minio/minio
    container_name: 'minio_service_container'
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: adminMinio
    command: server /data --console-address ":9001"

  minio-setup:
    image: minio/mc
    depends_on:
      - minio
    environment:
      MC_HOST: http://root:adminMinio@minio:9000
    entrypoint: >
      /bin/sh -c "
               echo Waiting for Minio...
               until mc alias set minio http://minio:9000 root adminMinio; do
                sleep 2;
                done;
                mc mb --ignore-existing minio/dev-bucket;
                echo Bucket created;
                exit 0;
                     "


volumes:
  pg_data:
  keycloak_pg_data:

