server:
  port: 8085
  tomcat:
    max-http-header-size: 16384


spring:
  application:
    name: LMS-system

  datasource:
    url: jdbc:postgresql://localhost:5433/LMS_System
    username: LMS_System_user
    password: admin1234


  jpa:
    hibernate:
      ddl-auto: validate


  flyway:
    enabled: true
    locations: classpath:db/migration


  security:
    oauth2:
      resourceserver:
        jwt:
         issuer-uri: http://localhost:8080/realms/LMS

  minio:
    url: ${MINIO_URL:http://localhost:9000}
    user: ${MINIO_USER:root}
    password: ${MINIO_PASSWORD:adminMinio}
    bucket: dev-bucket

  keycloak:
    auth-server-url: http://localhost:8080
    realm: LMS
    client-id: lms-backend
    client-secret: ${KEYCLOAK_CLIENT_SECRET:nymdyqI4rHEmH3K9drBW7t8CRZyYpJea}
    admin-realm: master
    admin-client-id: admin-cli
    admin-client-secret: ${KEYCLOAK_ADMIN_SECRET:myAdminSecret}

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB


