server:
  port: 8085


spring:
  application:
    name: LMS-system

  datasource:
    url: jdbc:postgresql://localhost:5433/LMS_System
    username: LMS_System_user
    password: admin1234

  jpa:
    hibernate:
      ddl-auto: update


  flyway:
    enabled: true
    locations: classpath:db/migration

  spring:
    security:
      oauth2:
        resourceserver:
          jwt:
            issuer-uri: http://localhost:8080/realms/lms-realm
